CREATE TABLE IF NOT EXISTS cambio ( id BIGINT NOT NULL AUTO_INCREMENT, monto DECIMAL(10,2) NOT NULL, monedaOrigen VARCHAR(255) NOT NULL, monedaDestino VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL, montoConvertido DECIMAL(10,2) NOT NULL, tasaCambio DECIMAL(10,2), PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS rol (idRol BIGINT NOT NULL AUTO_INCREMENT, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (idRol));

CREATE TABLE IF NOT EXISTS usuario ( idUsuario BIGINT NOT NULL AUTO_INCREMENT, usuario VARCHAR(255) NOT NULL, clave VARCHAR(255) NOT NULL, estado BOOLEAN NOT NULL, PRIMARY KEY (idUsuario));

CREATE TABLE IF NOT EXISTS usuario_rol (  idUsuario BIGINT NOT NULL, idRol BIGINT NOT NULL, FOREIGN KEY (idUsuario) REFERENCES usuario(idUsuario), FOREIGN KEY (idRol) REFERENCES rol(idRol),
  PRIMARY KEY (idUsuario, idRol));

INSERT INTO usuario (usuario, clave, estado)
VALUES ('arsides', '$2a$12$vNxfcQpSIN.0Uns420Y00eHoSGe.hgiDI1PMHzv2r5JjvQIwExN4q', TRUE);